### ISSUE TITLE
how do I attach Go Forward/Back to an event handler nice utility tool btw

### ISSUE THREAD

**Issue by sduzair** [tahir-hassan/PSLocationHistory#1]
I tried this:
```powershell
Set-PSReadLineKeyHandler -Chord 'Ctrl+b' -ScriptBlock {
	Go-Forward
}

Function Go-Forward {
    if (($script:LocationHistoryPointer -eq 0 -and ($script:LocationHistory.Count -eq 0)) -or ($script:LocationHistoryPointer -eq ($script:LocationHistory.Count - 1))) {
		Write-Host 'No "Forward" location';
	} else {
		$script:LocationHistoryPointer = $script:LocationHistoryPointer + 1;
		Set-Location $script:LocationHistory[$script:LocationHistoryPointer];
	}
}
```

I see the following exported commands:

Function        Add-PSLocationHistoryEventHandler                  1.29       PSLocationHistory
Function        Disable-LocationHistory                            1.29       PSLocationHistory
Function        Enable-LocationHistory                             1.29       PSLocationHistory
Function        Enter-RecentLocation                               1.29       PSLocationHistory
Function        Get-RecentLocation                                 1.29       PSLocationHistory
Function        prompt                                             1.29       PSLocationHistory
Function        Set-LocationWithHistory                            1.29       PSLocationHistory

**Comment by tahir-hassan** [comment]
What happens when you press control b?

**Comment by sduzair** [comment]
I get an error saying 
```powershell
InvalidOperation:
Line |
   6 |  Set-Location $script:LocationHistory[$script:LocationHistoryPointer];
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot index into a null array.
```

Anyways I got it to work when I learnt about `cd +` and `cd -`. Thanks anyways this is what I am using now.
```powershell
Set-PSReadLineKeyHandler -Key 'Alt+LeftArrow' `
     -BriefDescription 'PreviousDirectoryInHistory' `
     -ScriptBlock {
     [Microsoft.PowerShell.PSConsoleReadLine]::RevertLine()
     try { Set-Location - }
     catch { return }
     [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
 }
```
